# Welcome to Jekyll!
# Site settings
title: "Time: Philosophy & Physics"
description: "A research blog and reading log exploring the nature of time through the lenses of physics, philosophy, and data."
url: "https://github.io"
baseurl: "/mytime"
github_username: suhsunghee
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5 
paginate_path: /page:num/
timezone: America/New_York # Change this to your preferred time zone if desired

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# Sidebar Profile Configuration
author:
  name   : "Sunghee Suh"
  avatar : yamlauthor:
  name   : "Sunghee Suh"
  avatar : "/assets/images/IMG_0341.jpeg" # You can add a profile image here later
  bio    : "Researching the physics, philosophy, and perception of time."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"

# Bottom Footer Configuration
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com"

defaults:
  # _posts Settings
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false # Set to false since you don't have a comment system set up yet
      share: true
      related: true
  # _pages Settings
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
